/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ProductCategory = IDL.Variant({
  'Home' : IDL.Null,
  'Books' : IDL.Null,
  'Fashion' : IDL.Null,
  'Others' : IDL.Null,
  'Beauty' : IDL.Null,
  'Electronics' : IDL.Null,
  'Sports' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ProductId = IDL.Nat;
export const UserId = IDL.Principal;
export const OrderId = IDL.Nat;
export const ProductStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Product = IDL.Record({
  'id' : ProductId,
  'status' : ProductStatus,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'quantity' : IDL.Nat,
  'category' : ProductCategory,
  'sellerId' : UserId,
  'image' : ExternalBlob,
  'price' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'seller' : IDL.Null,
  'buyer' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'principal' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : IDL.Text,
});
export const VerificationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const SellerProfile = IDL.Record({
  'createdAt' : Timestamp,
  'businessName' : IDL.Text,
  'description' : IDL.Text,
  'sellerId' : UserId,
  'verificationStatus' : VerificationStatus,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'processing' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'priceSnapshot' : IDL.Nat,
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'deliveryAddress' : IDL.Text,
  'total' : IDL.Nat,
  'createdAt' : Timestamp,
  'buyerId' : UserId,
  'items' : IDL.Vec(OrderItem),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, ProductCategory, ExternalBlob, IDL.Nat],
      [ProductId],
      [],
    ),
  'approveProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'approveSeller' : IDL.Func([UserId], [IDL.Bool], []),
  'cancelOrder' : IDL.Func([OrderId], [IDL.Bool], []),
  'deleteMyProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'editProduct' : IDL.Func(
      [
        ProductId,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        ProductCategory,
        ExternalBlob,
        IDL.Nat,
      ],
      [IDL.Bool],
      [],
    ),
  'filterProductsByCategory' : IDL.Func(
      [ProductCategory],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getFeaturedProducts' : IDL.Func([IDL.Nat], [IDL.Vec(Product)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getMySellerProfile' : IDL.Func([], [IDL.Opt(SellerProfile)], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getSellerProfile' : IDL.Func([UserId], [IDL.Opt(SellerProfile)], ['query']),
  'getSellerRevenue' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'isApprovedSeller' : IDL.Func([UserId], [IDL.Bool], ['query']),
  'listAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'listApprovedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'listMyProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listPendingProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listPendingSellers' : IDL.Func([], [IDL.Vec(SellerProfile)], ['query']),
  'listSellerOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'placeOrder' : IDL.Func([IDL.Vec(OrderItem), IDL.Text], [OrderId], []),
  'registerAsSeller' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'rejectProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'rejectSeller' : IDL.Func([UserId], [IDL.Bool], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ProductCategory = IDL.Variant({
    'Home' : IDL.Null,
    'Books' : IDL.Null,
    'Fashion' : IDL.Null,
    'Others' : IDL.Null,
    'Beauty' : IDL.Null,
    'Electronics' : IDL.Null,
    'Sports' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ProductId = IDL.Nat;
  const UserId = IDL.Principal;
  const OrderId = IDL.Nat;
  const ProductStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Product = IDL.Record({
    'id' : ProductId,
    'status' : ProductStatus,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'quantity' : IDL.Nat,
    'category' : ProductCategory,
    'sellerId' : UserId,
    'image' : ExternalBlob,
    'price' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'seller' : IDL.Null,
    'buyer' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'principal' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  const VerificationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const SellerProfile = IDL.Record({
    'createdAt' : Timestamp,
    'businessName' : IDL.Text,
    'description' : IDL.Text,
    'sellerId' : UserId,
    'verificationStatus' : VerificationStatus,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'processing' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'priceSnapshot' : IDL.Nat,
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'deliveryAddress' : IDL.Text,
    'total' : IDL.Nat,
    'createdAt' : Timestamp,
    'buyerId' : UserId,
    'items' : IDL.Vec(OrderItem),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, ProductCategory, ExternalBlob, IDL.Nat],
        [ProductId],
        [],
      ),
    'approveProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'approveSeller' : IDL.Func([UserId], [IDL.Bool], []),
    'cancelOrder' : IDL.Func([OrderId], [IDL.Bool], []),
    'deleteMyProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'editProduct' : IDL.Func(
        [
          ProductId,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          ProductCategory,
          ExternalBlob,
          IDL.Nat,
        ],
        [IDL.Bool],
        [],
      ),
    'filterProductsByCategory' : IDL.Func(
        [ProductCategory],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getFeaturedProducts' : IDL.Func([IDL.Nat], [IDL.Vec(Product)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getMySellerProfile' : IDL.Func([], [IDL.Opt(SellerProfile)], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getSellerProfile' : IDL.Func(
        [UserId],
        [IDL.Opt(SellerProfile)],
        ['query'],
      ),
    'getSellerRevenue' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'isApprovedSeller' : IDL.Func([UserId], [IDL.Bool], ['query']),
    'listAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'listApprovedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'listMyProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listPendingProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listPendingSellers' : IDL.Func([], [IDL.Vec(SellerProfile)], ['query']),
    'listSellerOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'placeOrder' : IDL.Func([IDL.Vec(OrderItem), IDL.Text], [OrderId], []),
    'registerAsSeller' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'rejectProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'rejectSeller' : IDL.Func([UserId], [IDL.Bool], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };