/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'deliveryAddress' : string,
  'total' : bigint,
  'createdAt' : Timestamp,
  'buyerId' : UserId,
  'items' : Array<OrderItem>,
}
export type OrderId = bigint;
export interface OrderItem {
  'priceSnapshot' : bigint,
  'productId' : ProductId,
  'quantity' : bigint,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'processing' : null };
export interface Product {
  'id' : ProductId,
  'status' : ProductStatus,
  'title' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'quantity' : bigint,
  'category' : ProductCategory,
  'sellerId' : UserId,
  'image' : ExternalBlob,
  'price' : bigint,
}
export type ProductCategory = { 'Home' : null } |
  { 'Books' : null } |
  { 'Fashion' : null } |
  { 'Others' : null } |
  { 'Beauty' : null } |
  { 'Electronics' : null } |
  { 'Sports' : null };
export type ProductId = bigint;
export type ProductStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface SellerProfile {
  'createdAt' : Timestamp,
  'businessName' : string,
  'description' : string,
  'sellerId' : UserId,
  'verificationStatus' : VerificationStatus,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile {
  'principal' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'seller' : null } |
  { 'buyer' : null };
export type VerificationStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addProduct' : ActorMethod<
    [string, string, bigint, ProductCategory, ExternalBlob, bigint],
    ProductId
  >,
  'approveProduct' : ActorMethod<[ProductId], boolean>,
  'approveSeller' : ActorMethod<[UserId], boolean>,
  'cancelOrder' : ActorMethod<[OrderId], boolean>,
  'deleteMyProduct' : ActorMethod<[ProductId], boolean>,
  'editProduct' : ActorMethod<
    [ProductId, string, string, bigint, ProductCategory, ExternalBlob, bigint],
    boolean
  >,
  'filterProductsByCategory' : ActorMethod<[ProductCategory], Array<Product>>,
  'getFeaturedProducts' : ActorMethod<[bigint], Array<Product>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getMySellerProfile' : ActorMethod<[], [] | [SellerProfile]>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getSellerProfile' : ActorMethod<[UserId], [] | [SellerProfile]>,
  'getSellerRevenue' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'isApprovedSeller' : ActorMethod<[UserId], boolean>,
  'listAllProducts' : ActorMethod<[], Array<Product>>,
  'listAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'listApprovedProducts' : ActorMethod<[], Array<Product>>,
  'listMyOrders' : ActorMethod<[], Array<Order>>,
  'listMyProducts' : ActorMethod<[], Array<Product>>,
  'listPendingProducts' : ActorMethod<[], Array<Product>>,
  'listPendingSellers' : ActorMethod<[], Array<SellerProfile>>,
  'listSellerOrders' : ActorMethod<[], Array<Order>>,
  'placeOrder' : ActorMethod<[Array<OrderItem>, string], OrderId>,
  'registerAsSeller' : ActorMethod<[string, string], boolean>,
  'registerUser' : ActorMethod<[string, string], boolean>,
  'rejectProduct' : ActorMethod<[ProductId], boolean>,
  'rejectSeller' : ActorMethod<[UserId], boolean>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];